### ISSUE TITLE
[Bug]: Sidebar does not scroll on home page

### ISSUE THREAD

**Issue by richford** [neuroneural/brainchop#18]
On the home page of brainchop.org, the sidebar (the one with options "Open Brain T1 MRI," "Segmentation Options," etc) does not scroll and is cut off at the bottom on my Macbook. Would it be possible to make the sidebar scrollable?

Also, perhaps you could make each of the sidebar cards collapsible so that the user could hide them when they don't want them.

ref: [JOSS Review](https://github.com/openjournals/joss-reviews/issues/5098)

**Comment by Mmasoud1** [comment]
Thank you,  I added a scroll bar to the left mini forms of tool options. Try, please. 

For the collapsible enhancement,  currently, it raises some styling issues with the UI while try embedding the mini forms with accordion control since Webix doesn't support such an integration. We will keep that enhancement idea for future versions subject to finding a feasible workaround or performing major stylish refactoring to the side forms.  Till then we may consider the current issue closed for now.
